<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>trailing-whitespace</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.trailing-whitespace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s\s+)$</string>
			<key>name</key>
			<string>source.invalid.trailing-whitespace</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source</string>
	<key>uuid</key>
	<string>405B1A36-F924-4175-9CBF-914B2863DAE3</string>
</dict>
</plist>
